### ISSUE TITLE
Consul CA intermediate cert TTL parameter not honoring its value (IntermediateCertTTL) 

### ISSUE THREAD

**Issue by bvikhe** [hashicorp/consul#15199]
#### Overview of the Issue

We wanted to update the IntermediateCertTTL value with our intended one, update was successful as we see its updated in below endpoints output.

**connect/ca/configuration**

But when we read the below endpoint after config updated, we saw 6days intermediate TTL.

connect/ca/roots

#Server info

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = c6d0f9ec
        version = 1.13.1
        version_metadata =
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.44.182.126:8300
        server = true
raft:
        applied_index = 335
        commit_index = 335
        fsm_pending = 0
        last_contact = 24.646021ms
        last_log_index = 335
        last_log_term = 5
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:40e1784f-d6f4-a98d-26f1-2c9fd53a4166 Address:10.44.182.125:8300} {Suffrage:Voter ID:edafe015-c069-4496-add3-2f92ef2040df Address:10.44.182.127:8300} {Suffrage:Voter ID:65f8d5ed-2e97-58b7-eb8d-6eb353c79d12 Address:10.44.182.126:8300}]
        latest_configuration_index = 0
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 5
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 125
        max_procs = 4
        os = linux
        version = go1.18.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 5
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 13
        members = 3
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0

```
#Operating system and Environment details

3 nodes consul cluster, OS : CentOS 7.9

**Comment by jkirschner-hashicorp** [comment]
Hi @bvikhe,

Are you using Vault as the CA provider?

If so, there was a bug preventing the IntermediateCertTTL from being updated after creation: https://github.com/hashicorp/consul/pull/14516. That bug is fixed in 1.13.2, though we strongly recommend upgrading to 1.13.3 instead. Please review the associated upgrade instructions: https://developer.hashicorp.com/consul/docs/upgrading/upgrade-specific#modify-vault-policy-for-vault-ca-provider

**Comment by bvikhe** [comment]
@jkirschner-hashicorp ,  

Thanks, Will give it a try.

**Comment by bvikhe** [comment]
@jkirschner-hashicorp , 

Tried with consul-1.13.3 as well and still same issue, to verify we are using below steps.

1. upgraded consul to 1.13.3
2. updated connect ca config at /v1/connect/ca/configuration. (IntermediateCertTTL, LeafCertTTL, RotationPeriod)
3. read config at /v1/connect/ca/roots

Result is Active intermediate CA is still showing 6 days validity.

Am I missing something ?

**Comment by jkirschner-hashicorp** [comment]
Hi @bvikhe,

Can you confirm whether you modified the Vault policy associated with the Vault token/auth method Consul is using to connect to the Vault PKI secrets engine? It needs to include permissions to update the configuration (the "tune" endpoint) on the intermediate PKI path.

```
# Needed for Consul 1.11+
path "/sys/mounts/connect_inter/tune" {
  capabilities = [ "update" ]
}
```

**Comment by bvikhe** [comment]
@jkirschner-hashicorp , 

we are using vault but certs and chain is externally created from vault and then imported to consul as we have disconnected environment consul is not directly connecting to vault for creating CA.

**Comment by jkirschner-hashicorp** [comment]
Hi @bvikhe,

What Vault policy is associated with the Vault token or Vault auth method the Consul Connect CA uses to authenticate with Vault? That might help me understand whether there's a disconnect between the permissions granted and the permissions Consul currently requires.

I think the underlying cause of the behavior you observed is actually different in 1.13.1 vs 1.13.3.

In 1.13.1, the intermediate cert TTL parameter was only being used:

- [As the intermediate cert's `ttl` when generating the intermediate CA's CSR](https://github.com/hashicorp/consul/blob/c6d0f9ecc48e2044db04f5795e997bd9179586de/agent/connect/ca/provider_vault.go#L557)
- [If no CA existed at the intermediate PKI path, a CA would be initialized with intermediate cert TTL set as the `MaxLeaseTTL`](https://github.com/hashicorp/consul/blob/c6d0f9ecc48e2044db04f5795e997bd9179586de/agent/connect/ca/provider_vault.go#L373-L379)

In your original report, you mentioned that you updated the IntermediateCertTTL value with our intended one, but then saw an intermediate TTL of 6 days. Can you provide me more details on:
- The initial TTL of the intermediate cert?
- The new IntermediateCertTTL that you set?
- The response from `connect/ca/roots` (with any sensitive details scrubbed) showing that the TTL didn't change as you intended?

I'm not personally familiar with the conditions under which Consul would generate a new intermediate cert. I know it attempts to generate a new intermediate cert at 50% of the intermediate TTL (for purposes of rotation), but I'm not familiar with the other cases (if any)? I wonder if the configuration was changed, but will only take effect the next time a new intermediate cert would be generated.

**Comment by pavansh** [comment]
Hi @jkirschner-hashicorp 

**1. The initial TTL of the intermediate cert?**
{
  "Provider": "consul",
  "Config": {
    "IntermediateCertTTL": "8760h0m0s",
    "PrivateKey": "xxx",
    "RootCert": "xxx"
  },
  "State": null,
  "ForceWithoutCrossSigning": false,
  "CreateIndex": 5,
  "ModifyIndex": 38
}

**2. The new IntermediateCertTTL that you set?**
     9 months

**3. The response from connect/ca/roots (with any sensitive details scrubbed) showing that the TTL didn't change as you intended?**
{
  "ActiveRootID": "xxx",
  "TrustDomain": "xxx",
  "Roots": [
    {
      "ID": "xxx",
      "Name": "Consul CA Primary Cert",
      "SerialNumber": xxx,
      "SigningKeyID": "xxx",
      "ExternalTrustDomain": "xxx",
      "NotBefore": "2022-11-09T10:39:28Z",
      "NotAfter": "2023-12-04T10:39:58Z",
      "RootCert": "xxx",
      "IntermediateCerts": [ 
        **"xxx"					// This Active Intermediate Cert is valid for 6 days only.**
      ],
      "Active": true,
      "PrivateKeyType": "ec",
      "PrivateKeyBits": 256,
      "CreateIndex": 27,
      "ModifyIndex": 27
    },
    {
      "ID": "xxx",
      "Name": "Consul CA Primary Cert",
      "SerialNumber": 7,
      "SigningKeyID": "xxx",
      "ExternalTrustDomain": "xxx",
      "NotBefore": "2022-11-09T10:39:22Z",
      "NotAfter": "2032-11-06T10:39:22Z",
      "RootCert": "xxx",
      "IntermediateCerts": null,
      "Active": false,
      "PrivateKeyType": "ec",
      "PrivateKeyBits": 256,
      "CreateIndex": 9,
      "ModifyIndex": 27
    }
  ]
}

**Comment by jkirschner-hashicorp** [comment]
Hi @pavansh,

Making sure I understand, your report is separate from @bvikhe 's, and you were using Consul's built-in Connect CA provider, rather than using Vault as a Connect CA provider?

**Comment by pavansh** [comment]
Hi @jkirschner-hashicorp 
we are team, working on same issue.
it is also not working with Consul's built-in connect CA provider.

**Comment by jkirschner-hashicorp** [comment]
Hi @pavansh , @bvikhe,

From your response (1), it looks like the intermediate cert TTL was initially 1 year (8760 hours). **What was the remaining lifetime of the current intermediate cert at this point, before making the call to modify the intermediate cert TTL?**

It sounds like, after you modified the intermediate cert TTL config to 9 months, the remaining lifetime of the intermediate cert was 6 days. I wonder whether the remaining lifetime was 6 days even before you modified the TTL config. I haven't checked the code paths to verify this theory yet, but I'm wondering whether changing the TTL config has no effect on the current intermediate cert, but will only apply to the subsequent cert when rotation occurs.

That said, I'm surprised that the active intermediate cert wouldn't have been rotated/replaced by a new one automatically if it only had 6 days before expiry. **Which version of Vault were you using?** There's a [known issue when using Vault 1.11+ as a Connect CA](https://github.com/hashicorp/consul/issues/15217) that a fix was just released for yesterday. That said, I know you mentioned that you saw the same behavior with Consul's built-in connect CA provider, so maybe this isn't related.

Lastly, what's your current status? We're past the 6 day lifetime of the intermediate cert from your last comments. Did the intermediate cert get rotated successfully? Does the remaining lifetime of the new intermediate cert align with the new TTL you specified?

**Comment by bvikhe** [comment]
@jkirschner-hashicorp , 

1.   below is our process(not sure how vault can be issue here)

* Create Intermediate CA cert from vault (vault and consul is not in connected environment)
* Applied CA cert to consul connect(now consul is acting cert provider from here)

2. We are using Vault version 1.10+
3. Before and After config change intermediate Cert TTL does not change, (point is it take no effect after 6 days we see cert expired and not renewed with new ttl value)

If possible for you, can we connect on this ? 


With Regards, 
Bankat Vikhe

**Comment by jkirschner-hashicorp** [comment]
Hi @bvikhe,

Please contact me using the details in my Github profile and reference this issue. Let's find some time to talk in January (after winter holidays).

**Comment by kisunji** [comment]
Hello @pavansh and @bvikhe,

### Are you using secondary datacenters?
If so, [IntermediateCertTTL](https://developer.hashicorp.com/consul/docs/connect/ca/consul#intermediatecertttl) must be configured on the primary for it to take effect.

### Are you seeing more than one PEM in `IntermediateCerts`?
In a secondary datacenter, it is normal to have one intermediate cert close to expiry and a newer one. Any expired certs are eventually removed.

> Before and After config change intermediate Cert TTL does not change

Changing `IntermediateCertTTL` will not modify any existing certs. It affects new intermediates that are signed by the primary datacenter so you will have to wait until the latest `IntermediateCert` PEM is half-way to expiring before you see any updates.

In the meantime you can [query the current configuration](https://developer.hashicorp.com/consul/api-docs/connect/ca#get-ca-configuration) on your primary to check that `IntermediateCertTTL` has been updated.
```sh
$ curl http://127.0.0.1:8500/v1/connect/ca/configuration?dc=dc1
```
```sh
{
  "Provider": "consul",
  "Config": {
    "LeafCertTTL": "72h",
    "IntermediateCertTTL": "8760h"
  },
  "CreateIndex": 5,
  "ModifyIndex": 5
}
```

**Comment by jkirschner-hashicorp** [comment]
Hi @pavansh and @bvikhe,

Just following up on this. When you have the chance, can you respond to @kisunji 's questions so we're better able to assist and understand whether there are any opportunities to improve usability here?

**Comment by kisunji** [comment]
Closing due to lack of response. Please feel free to tag us in a comment with updates.
