### ISSUE TITLE
Consul intermittent failure when cycling servers

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/consul#1554]
I have a 3-server cluster, with lots of clients attached. I am using the DNS service in this test.

I regularly dig one of my consul clients for a dns entry like this:

```
while [ 1 ] ;do echo "NEW DIG" ; dig @localhost foo.service.dc1.consul +short ; sleep 1 ; done
```

Next, I momentarily stop one of the consul servers, for a period of 60 seconds say (whilst I reconfigure it).

As soon as I stop it, there is a period of 1-3 seconds when the dig fails to respond with anything.

Is this expected behaviour? Is there any way to prevent this tiny bit of "downtime" in the DNS service? Thanks

**Comment by cruatta** [comment]
I think I can answer this. Please correct me if I'm wrong. During a leader election, there will briefly be no leader. Since, by default, all DNS queries are answered by the leader, during the election no results can be returned. Allow stale reads in your consul agent config and you should solve this problem. 
https://www.consul.io/docs/agent/options.html#allow_stale

You can also turn on DNS caching using something like DNSMasq to solve the problem with properly configured TTLs.

**Comment by hesamg** [comment]
We have the exact same issue where we reboot a node (not the leader) within the cluster, and we don't get any DNS response for a few seconds.  We have turned on allow_stale, but that does not solve this issue.

**Comment by slackpad** [comment]
I think the issue is that, even if `allow_stale` is turned on but you get unlucky and your client was connected to the server that was cycled, at least one request will fail and get cached. We should be able to improve this by adding a retry and an attempt to connect to another server, since the cost of a cached (in DNS) response with an error is fairly high.

**Comment by slackpad** [comment]
This was fixed in https://github.com/hashicorp/consul/pull/3561 (and is related to https://github.com/hashicorp/consul/issues/3514).
