### ISSUE TITLE
Allow all output updates during CheckUpdateInterval after a state change

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#1982]
This tracks an enhancement we identified under https://github.com/hashicorp/consul/issues/1057. You are currently forced to wait the `CheckUpdateInterval` after registering a new check before output will be accepted (unless the state changes). We should allow all output up to `CheckUpdateInterval` _after_ a state change (or the initial registration of the check) so that startup transients can be observed, and then rate limit as usual after that.

**Comment by vchekan** [comment]
If I monitor my health checks for long enough ~20min, I can see Output field to be filled out or go empty at random intervals of time. I mean it goes on and off and than on with ~5min intervals. Some checks would have output and some would not.
Does this sound like this bug or something else?
v0.6.4

**Comment by arcz** [comment]
I have similar issues as @vchekan, same version.

**Comment by ezraroi** [comment]
Me too, is this fixed in 0.7?

**Comment by arcz** [comment]
One thing I noticed, problem appears for me when running one server instance, on production where I'm running 3 server cluster there seem no issues.

**Comment by arcz** [comment]
I updated single running server to 0.7.0 and seems that issue is gone.

**Comment by adveres** [comment]
+1 It's frustrating to have all of my checks be green, but their output reflects a previous "run" of the check (that was passing but had different output).

```
# consul -v
Consul v0.7.4
```

The behavior I have noticed in the Consul UI is that the output does not get updated unless there is a state change.

**Comment by Brennan-VanderLaan** [comment]
I'm still seeing this issue when doing TTL checks with updated output, but the same state. The UI does not reflect the latest output unless there is a state change. Am I just missing something?

**Comment by slackpad** [comment]
@Brennan-VanderLaan that's currently how things are working - we rate-limit output updates if the state doesn't change. This feature would improve that.

**Comment by dkrutsko** [comment]
Hello, has there been any updates on this?
