### ISSUE TITLE
New agent unable to join using old key, then can't join using current key

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#719]
# steps to reproduce
## start server

```
consul agent -data-dir $(mktemp -d) -server -bootstrap -encrypt FLSuISVKvZ9bJA69VFmigg==
```
## start first agent

```
consul agent -data-dir $(mktemp -d) -join 172.17.0.14 -encrypt FLSuISVKvZ9bJA69VFmigg==`
```
## rotate key, preserving original one

```
k=$( consul keygen )
consul keyring -install=$k
consul keyring -use=$k
```
## attempt to start 2nd agent with old key, get failure

```
# consul agent -data-dir /tmp/tmp.2pqVpwejJr -join 172.17.0.14 -encrypt FLSuISVKvZ9bJA69VFmigg==
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Joining cluster...
==> Reading remote state failed: No installed keys could decrypt the message
```
## attempt to start 2nd agent with current key, also get failure

```
# consul agent -data-dir /tmp/tmp.2pqVpwejJr -join 172.17.0.14 -encrypt AifVtRH2vbkPwaRuandoQQ==
==> WARNING: LAN keyring exists but -encrypt given, ignoring
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Joining cluster...
==> Reading remote state failed: No installed keys could decrypt the message
```

The only way to get the new agent to join, then, is to delete the data dir.

**Comment by blalor** [comment]
Clarification: removing `$data_dir/serf/local.keyring` makes it possible for the new agent to join.

I'm trying to figure out how to manage key rotation in concert with a CM system that is used to bootstrap new agents.

**Comment by ryanuber** [comment]
@blalor so this is tricky. The problem you are facing is that any given node will *only* send messages using the primary encryption key. We don't encrypt replies based on the the key used from the requestor. Since your 2nd node never knew about the new key, it was unable to decrypt the response sent to it from the original node, and therefore could not join. Normally a key rotation should happen when all nodes are available to receive the new key, and not during a deploy. I'll think more about how we can make this nicer.

**Comment by blalor** [comment]
The real problem to me is that the new agent is writing `local.keyring` before it's verified that it can use the given key.  Per #718, the local keyring takes precedence over whatever configuration options are provided.  So, not being able to join the cluster because the key is wrong is fine.  Having to root around in the data-dir to clean out cruft so that the agent will use the provided key is _not_ fine.  Does that make sense?

**Comment by ryanuber** [comment]
@blalor makes sense, I'll see if we can do something more intelligent for the initial keyring persistence. For the time being, you could work around it by removing the data directory if the initial start-join fails.

**Comment by kyhavlov** [comment]
Can't reproduce as of 0.8.3, if you're still seeing this with the latest version we can re-open this.

**Comment by sidhurana** [comment]
I am using consul v0.8.4 and getting same error.  I had to remove local.keyring file and then it started working.

I am also not sure how it can work with autoscaling new consul server. As while bootstrapping it creates new key with consul keygen and client will start failing as it has different encryption key. 

Any ideas how to push new keys to client from server ? Or if we can pertain old encryption key in new instance ?

**Comment by shantanugadgil** [comment]
I am seeing thin on my Consul 0.8.5 cluster when I moved my VMs from one subnet into another.

**Comment by kyhavlov** [comment]
@shantanugadgil can you reproduce it with the same steps/ordering as above?

**Comment by shantanugadgil** [comment]
Hi,

My scenario is different, I'll explain the details:

I have 1 Ubuntu 16.04 VM and about 8-10 LXD containers in it.
There is a Consul agent running in server mode on the Ubuntu 16.04
Each LXD has a Consul agent running in client mode; connecting to the server running on the base machine.
The LXDs are running on an internal bridge; LXD IPs are 10.x.x.x
The base machine has an interface `lxdbr0` which is for all the LXD containers

These messages popped up when:
I did a backup of the VM from one physical host in one network (/22) and moved it to another virtualization host in another network (/26).

What I got was large amount of messages of the following type:
```
memberlist: failed to receive: No installed keys could decrypt the message from=XX.XX.XX.XX:NNNNN
```
These messages were seen in all the client Consul's log messages.

Rather than fighting with it, I fixed it as:
Stop all Consul's.
Then I deleted the consul data dir for all consuls, including server and all clients.
Changes the `encrypt` key (just for good measure).
Restarted all consuls.

Then things started working fine.

**Comment by EugenMayer** [comment]
This still happenes with 1.0.7 e.g. when you redo a consul server from scratch, getting a new token, and also deploy the new gossip token to the clients - on starting the clients you see:

```
* Failed to join 10.249.249.254: No installed keys could decrypt the message)
```

**Comment by sbilello** [comment]
This happens also on 1.0.6. I had to set the same encryption key between server and client to let another consul client node join the cluster :(
Log from the server:
```2018/11/21 05:13:12 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=172.24.158.223:56038````
172.24.158.223 is the new host that tries to join the cluster using a key that is valid from the other node that already joined the cluster.

**Comment by ryanuber** [comment]
I am pretty out of context at this point, but if I’m right the original issue might be fixed easily. When joining a new node using the `-encrypt` flag, consul should not write out the keyring file until we are successfully joined to the cluster. `-encrypt` is meant as a convenience for the initial join and usually has no effect on agent restarts.

Keep in mind that you need the _current_ encryption key to successfully join the cluster or you will see errors. This is because the servers will encrypt their responses using their primary key only. You cannot join using a key which is not the primary key of the node you are joining.

**Comment by banks** [comment]
Hi @sbilello, @EugenMayer, there are several subtelties around key rotations in presence of failures and they depend on a lot of things including, order you completed them, what was up and down at the time, whether you have disabled the keyring file or not etc.

It's quite possible you are still hitting the same issue as originally described here which might be fixed as Ryan described, but it's hard to know that for sure given the limited information we have. It's also the case that the fix Ryan describes will not make every possible way of getting into a bad state go away so it's quite possible it wouldn't fix your issues anyway.

If you (or others who end up here) have a specific case, can you please open a new issue and describe the exact config and steps to get into a bad state (e.g. when and why different nodes were restarted/down/introduced to the cluster relative to keyring operations) so we can be clear on which specific issue causes it and whether it's something we can fix or just something we need to be clearer about in documentation?

I'm wary about re-opening this issue as it is because it's not clear to me all the various reports here are describing symptoms of the same issue.

**Comment by EugenMayer** [comment]
@banks IMHO ( no offense) those issues here need immediate reaction - the problem with all the issues here, mostly the hashicorp devs ask 3-4 months later for missing informations  - but most of us are forced to fix the issue in 1-3 days, we cannot wait and conserve this issues for months until you might get a reaction and so you rather will not get any useful additional informations of us - even if we would really like to (i would)

Do not get me wrong - i did not pay a cent and this means, i am not able to expect any reaction at all - so this was no demand or critic.

It's just the reality that you will rarely get the information and context informations of those issues here, if you do not react more or less instant to the report to gather and "conserve" all the needed details.

**Comment by isserd** [comment]
I had this issue and on agents -> stopping consul on the agents, removing the local keyring and local snapshot and then restarting agents

**Comment by zakabluk** [comment]
> I had this issue and on agents -> stopping consul on the agents, removing the local keyring and local snapshot and then restarting agents

It's help me.

**Comment by kolbasss** [comment]
I faced with this issue at last week - Consul 1.5.2
Can't add new cluster member after changing GOSSIP key.
Removing  $data_dir/serf/local.keyring and restarting all cluster members helped me

**Comment by shantanugadgil** [comment]
If you don't have immutable architecture, this could be codified in whichever config management system you use to do a Consul reset of these files, which can be run out of band as needed.

**Comment by karras** [comment]
Just faced the same issue on `Consul v1.6.1`. Cleaning up the old local.keyring entries resolved the problem on the agents side.
