### ISSUE TITLE
'Service does not exist' should not be fatal

### ISSUE THREAD

**Issue by nicholascapo** [hashicorp/consul#769]
Occasionally we have a server that crashes or is rebooted un-cleanly. On restart consul dies with an error:

    ==> Starting Consul agent...
    ==> Error starting agent: ServiceID "foo" does not exist

This requires manual intervention to remove the service from the consul data-dir and restart the services.

This error should not be fatal, and should simply result in the service not being available in the catalog.

An additional note: In this case the services are registered using the HTTP API not the config files.

**Comment by cetex** [comment]
Same here, it happens often on rebooting the cluster (which i'm doing due to testing)
Rebooted the cluster and got this error.
Current status: Can't start any consul agent, datacenter is currently down. consul data-dir most likely needs to be erased and kv/store needs to be recreated from scratch..

**Comment by armon** [comment]
Thanks for the report, tagging as a bug!

**Comment by cetex** [comment]
Great. How tricky is this to fix?
It's currently one of (very few things) holding us back from moving forward with deploy on consul on the rest of the DC.

**Comment by ryanuber** [comment]
I don't think this one will be too hard to fix. I'll take a look at it soon, although you'd have to build from master to get the fix since we have no release dates planned yet.

**Comment by cetex** [comment]
sure. i can build it and distribute it from my own repo as long as there's something that works. :)

**Comment by ryanuber** [comment]
Fixed by 04a2fae. We now warn and purge the erroneous check. Thanks!

**Comment by nicholascapo** [comment]
Sweet, thanks Ryan

**Comment by cetex** [comment]
Awesome, way faster than i thought possible ;)

**Comment by tonglil** [comment]
Mm, I think this is still happening?

I defined the service in a check.

Running 
```
Consul v0.6.3
Consul Protocol: 3 (Understands back to: 1)
```

**Comment by ryanuber** [comment]
Hi @tonglil,

Is this check inside of a config file? This fix is only to purge health checks which were submitted from the REST API, and whose services no longer exist when Consul is restarted. If the check is defined in a configuration file, you have to remove the check or the config file which contains it.

Hope that helps.

**Comment by tonglil** [comment]
Ah gotcha, thanks for the clarification @ryanuber.

Do you know what the reasoning is for making it fatal for config files?

**Comment by ryanuber** [comment]
No problem. I think it was mainly just the most logical course of action when a check is attempted to register against an unknown service. You would otherwise get a running Consul agent without the check or the service you specified, which seems rather unexpected. Let me know if I missed anything!
