### ISSUE TITLE
client upgrade (to 1.9.0): panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kpurdon** [hashicorp/consul#9317]
#### Overview of the Issue

After upgrading servers to 1.9.0 following the gradual rollout procedure (used for multiple other upgrades) clients are failing to start with the following error in logs:

`panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x24b95ec]`

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Upgrade a cluster w/ latest consul-helm (servers only to 1.9.0
2. Upgrade clients 
3. See clients fail w/ reported error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 2
	services = 2
build:
	prerelease =
	revision = ba7d9435
	version = 1.8.2
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 173
	max_procs = 4
	os = linux
	version = go1.14.6
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 29
	failed = 6
	health_score = 0
	intent_queue = 0
	left = 21
	member_time = 332154
	members = 52
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = a417fe51
	version = 1.9.0
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.12.7.21:8300
	server = true
raft:
	applied_index = 31162878
	commit_index = 31162878
	fsm_pending = 0
	last_contact = 69.020611ms
	last_log_index = 31162878
	last_log_term = 76
	last_snapshot_index = 31157764
	last_snapshot_term = 74
	latest_configuration = [{Suffrage:Voter ID:096ebb62-8a83-78ea-8a2f-6cdde14c2e16 Address:10.12.7.21:8300} {Suffrage:Voter ID:6a44cd9f-1142-3a54-53a5-f9123e03f69b Address:10.12.37.11:8300} {Suffrage:Voter ID:64f0fc75-6db5-3eb5-5b01-baaf7a2ab7f8 Address:10.12.15.104:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 76
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 546
	max_procs = 4
	os = linux
	version = go1.15.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 29
	failed = 2
	health_score = 0
	intent_queue = 0
	left = 3
	member_time = 332150
	members = 29
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 234
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

GKE via Consul-Helm -- Upgrade from 1.8.2 (0.24.0) -> 1.9.0 (0.27.0)

- Upgraded all helm chart versions first w/ 1.8.2
- Upgraded servers 1 by 1 to 1.9.0
- Started upgrade of all clients (issue here)

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

<img width="1589" alt="Screen Shot 2020-12-02 at 11 39 35 AM" src="https://user-images.githubusercontent.com/5130441/100917005-d008b300-3493-11eb-9684-6dd1d28b1582.png">

### Helm Values

```
global:
  datacenter: gcp

  tls:
    enabled: true
    enableAutoEncrypt: true

  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

server:
  image: consul:1.9.0

client:
  image: consul:1.9.0

ui:
  enabled: false

connectInject:
  enabled: true
  # require services to opt-in via annotations
  # https://www.consul.io/docs/platform/k8s/connect.html#consul-hashicorp-com-connect-inject
  default: false
```

**Comment by dnephin** [comment]
Thank you for the bug report! This looks like exactly the same panic as #8430 which was fixed in #8440 and released in version 1.8.2. Looking at [the code for 1.9.0, line 334 in that file is a blank line](https://github.com/hashicorp/consul/blob/release/1.9.0/agent/xds/server.go#L334). 

I see in the client info that the client is on version 1.8.2, which is very strange because that should be the version where it was fixed.  

If I'm understanding the fix correctly it seems like the envoy proxies would need to be restarted to pickup the new bootstrap config. Is it possible that you are using [envoy_bootstrap_json_tpl](https://www.consul.io/docs/connect/proxies/envoy#envoy_bootstrap_json_tpl) and the setting was not changed in the custom bootstrap config? Or maybe the envoy proxies need to be restarted to pickup that change that was added in Consul 1.8.2?

**Comment by kpurdon** [comment]
> Is it possible that you are using envoy_bootstrap_json_tpl and the setting was not changed in the custom bootstrap config?

I don't think so unless it's something in the helm chart itself.

> I believe the reason you are hitting the bug now is that it only occurs when the Consul client agent is restarted without the envoy proxy being restarted.

To be clear how would I restart the envoy proxies? Wouldn't this just be re-deploying connect enabled services? Or is there something on the server/client itself that needs restarted?

**Comment by dnephin** [comment]
I'm not all that familiar with the helm chart, so I asked my colleagues.

It sounds like if you re-deploy the connect enabled services it should restart the envoy proxies associated with those services. Upgrading the client agents does not restart the proxies.

**Comment by kpurdon** [comment]
That what I expected. All of the services had been restarted many times running on 1.8.2 which is why I would expect I had the fixed version. In a dev environment, I was able to blow away the install 1.8.2 and then upgrade to 1.9.0 w/ issue. However, it was definitely odd to hit this and keeps me pretty hesitant to upgrade in production environments since even rolling back to 1.8.2 didn't fix things.

**Comment by kpurdon** [comment]
I'm not sure if any real action can be taken here so I'm going to go ahead and close this. I was able to upgrade w/o this issue in production (though it wasn't totally smooth). I'll keep an eye out and re-open if I find anything useful.
